### ISSUE TITLE
NullReferenceException comes up after setting the long break time

### ISSUE THREAD

**Issue by jennyTG** [adrian-miasik/unity-pomodoro#100]
# User Bug Report

## Description
> 
> - After launching the program and finishing the tomato counters, the long break time doesn't start when clicking the play button. 

## Reproduction Steps
> 1. Launch application
> 2. Set the time for both work and break time
> 3. Let the timer finish
> 4. Set the time for the long break time
> 5. Click the play button
> 6. Notice how the timer doesn't start

## Impacted Version(s)
> - Version: 2.4.0

## Impacted Platform(s)
> - Windows
> - Android

## Expected Behaviour
> - Expected the timer to start after setting the time for long breaks

## Screenshots
> Here's a screenshot of the exception
![Screenshot (37)](https://user-images.githubusercontent.com/74051967/210739330-6cbdee8d-2cac-4ef5-bcd4-4ac0e8b9dd87.png)

## Additional Context/Comments
> - I can't pinpoint the reference variable that's causing the null exception since I'm not very familiar with the code. Hope you can give attention to this. Thanks!

**Comment by adrian-miasik** [comment]
Ah good catch. I'll get on this right away. 👍 

Looks like it's happening on the non-steam versions of the app.

It seems I forgot to check if the Steamworks API/implementation has been initialized or not, prior to running some Steamworks related code.

I'm trying to access the Steamworks API/methods without validating if it's running/been initialized. To fix this null ref we simply need to check if the Steamworks API is initialized and then run the associated Steam stat/canned achievement logic which is trying to be invoked here.

Funny because I do this check everywhere else for Steamworks related method calls, but seemed to have missed it here. Thanks for finding this.

**Comment by adrian-miasik** [comment]
I have a PR up addressing this issue: #101 
I'll be directing the PR into the hotfix branch.
I'll try to have a build up later this week. 

Thanks for reporting this @jennyTG !

**Comment by adrian-miasik** [comment]
Latest release (v2.4.1) is out with the appropriate fix:
https://github.com/adrian-miasik/unity-pomodoro/releases/tag/v2.4.1

Marking issue as complete, if it continues to appear in the latest version. Please re-open this ticket.

**Comment by jennyTG** [comment]
Sorry took me long to reply. It's working well now. Thank you very much for the fix!

**Comment by adrian-miasik** [comment]
Awesome, that's great to hear! Let me know if you run into any more issues :)

**Comment by jennyTG** [comment]
Sure! Thanks for the help again! Keep the great projects coming👍
