### ISSUE TITLE
Problems with Icons on MacOS Ventura w/ Apple Silicon

### ISSUE THREAD

**Issue by KingWazzack** [adrian-miasik/unity-pomodoro#109]
## Description
> Icon Images (Vectors?) not being drawn correctly
Tried restarting a couple times but issue is persistent. Doesn't impact funtionality however.

## Reproduction Steps
Opening the app, most of the icons are drawn incorrectly. Might be purely apple silicon based? Idk, don't have an Intel based Mac available to test

## Impacted Version(s)-
> - Version: 2.4.1

## Impacted Platform(s)
> - Mac OS Ventura 13.1 (Macbook Pro 14" model with M1 Pro)

## Screenshots
![Image](https://i.imgur.com/AXwPjTc.png)
![Image2](https://i.imgur.com/1ijfYo2.png)

##Edit

Just noticed #104 is about the same issue. But that was android based. So i'm leaving this issue open for now.

**Comment by adrian-miasik** [comment]
Hey @KingWazzack,

Thank you for reporting this.

I see your edit and you seemed to have found a similar bug this was related to. So while I don't have a mac workstation to iterate, test, debug, or verify with...I'm going to assume that the issue is related to Unity Cloud Builds and not Apple Silicon.

Once I'm at my workstation, I'll try to create a local mac OS build and upload that here. 
Perhaps you can verify for me if it's also persisting on that (local) build and not just UCB's.

It could also be an improper config on UCB, but we should probably verify first if this issue is coming from UCB's.

Will report back with a build a bit later!
I'll keep you updated.

**Comment by KingWazzack** [comment]
No problem! @adrian-miasik :)
Should you need any help testing it, i'd be happy to help.

**Comment by adrian-miasik** [comment]
That is very much appreciated!

I've made it back to my workstation and made a build locally. It can be found in the 2.4.1 release or you can download it directly here: https://github.com/adrian-miasik/unity-pomodoro/releases/download/v2.4.1/unity-pomodoro-2.4.1-mac-desktop-local.zip

This one is built locally (not UCB) and has fixed the Android issue in the past. Can you confirm if the build above also has these problematic icons please?

**Comment by KingWazzack** [comment]
No problem! 
Unfortunately i can't test right now since i'm at work. But once i get home i'll test it out for you! :)

**Comment by adrian-miasik** [comment]
Oh absolutely, totally understandable! 
Please take your time, it's no rush really. 
I appreciate the help nonetheless :D

**Comment by KingWazzack** [comment]
I just tried running the program. Unfortunately it's giving me the following error. :(
<img width="261" alt="Screenshot 2023-04-22 at 17 40 01" src="https://user-images.githubusercontent.com/61501251/233793772-7d9a77a9-2f1d-44a1-aeb2-f627b1b27b25.png">

**Comment by KingWazzack** [comment]
Ignore the message above, i just found out the MacOs builtin Archive Utility can sometimes break executables when unzipping a file. Tried it with 'The Unarchiver' and it works perfectly! So the issue is resolved! !  <img src="https://user-images.githubusercontent.com/61501251/233794122-6685e7b0-08e9-43e0-932e-2f4b00fb8c25.png"  width="220" height="200">

**Comment by adrian-miasik** [comment]
Ah okay glad to see the local build is running fine! I'll remove the UCB version from the 2.4.1 release so folks don't download and use the wrong one by mistake.

Also seeing as this was a UCB issue, I'll either have to investigate the cause and mess with the configs to produce an output that doesn't provide bugged visuals or I'll have to resort to local builds. 

Since UCB's is an expense, I'll opt for local builds for the time being.

But glad to hear the issue got resolved!
