### ISSUE TITLE
Audio not playing while minimized

### ISSUE THREAD

**Issue by rdelian** [adrian-miasik/unity-pomodoro#76]
# User Bug Report

## Description
- Alarm sounds are not playing if app is minimized in taskbar

## Reproduction Steps
1. Start session
2. Minimize Application

## Impacted Version(s)
- Version: 2.1.1

## Impacted Platform(s)
- UWP (I got the app from Microsoft Store)

## Expected Behavior:
- Prompt the user with a alarm sound even when the application is minimized.

**Comment by adrian-miasik** [comment]
Hey there @rdelian, 👋
Thanks for submitting a bug report.

I'm going to need a bit more information to try to reproduce this on my end.

- Can you confirm that the `Mute audio when out of focus` settings option is disabled when this happens? (See screenshot below)

![image](https://user-images.githubusercontent.com/12757380/166165522-c6c522a5-13e3-4be2-b1c4-eeef4ce96a21.png)

- Also can you verify for me that you aren't in Windows `Focus Assist` mode when this happens?

![image](https://user-images.githubusercontent.com/12757380/166165641-c8a73511-6a79-4d70-9e1b-2151a0370c5c.png)

**Comment by adrian-miasik** [comment]
Also, do you get prompted with a Windows Notification indicating that the timer has ended? 
It's possible the notification (along with the audio) is being suppressed.

**Comment by rdelian** [comment]
> Can you confirm that the Mute audio when out of focus settings option is disabled when this happens? 

Yes, is disabled

> Also can you verify for me that you aren't in Windows Focus Assist mode when this happens?

Focus Assist mode if Off

> do you get prompted with a Windows Notification indicating that the timer has ended?

I do get the notification

----

As soon as I open the app from taskbar the sounds plays, if I minimize it it stops. I also tried minimize it and look into the sound mixer and the app _looks_ like is playing 
![image](https://user-images.githubusercontent.com/25958136/166166393-304ec93d-c460-486b-be2d-a3cce19877ea.png)

**Comment by rdelian** [comment]
Looks like MuteSoundWhenOutOfFocus works in the reverse way. If I `enable` it I get the alarm sound even if minimized, but not the beep alarm when I dismis the window notification

**Comment by adrian-miasik** [comment]
Hmm, very odd behavior. So it sounds like the UI isn't matching the system setting. Might possibly be a front-end bug.

I've added in a factory restart into the application a couple versions back so that all the settings and visuals revert to their pre-defined initial values.

Try a factory restart first:
- You can do this by pressing `F5` in the app. (WARNING: Pressing `Yes` will reset your desired preferences)

Then check the `Mute Audio When Our Of Focus` settings option. Does it still works in this reverse manner after a factory reset?

**Comment by rdelian** [comment]
I tried and It still works the same way I described earlier, 

I didn't complile the project to test it but I think that's the issue:

https://github.com/adrian-miasik/unity-pomodoro/blob/496950b8389f9447ae318925cc4818b7180ec276/UnityPomodoro/Assets/AdrianMiasik/Scripts/UWP/UWPNotifications.cs#L42-L47

**Comment by adrian-miasik** [comment]
Ah, while minimized! Here I was...primarily thinking about the out of focus functionality. Heh.

However...
It seems when UWP applications are minimized, they become suspended.
> [UWP apps move to a suspended state when they are not running in the foreground. On desktop, this occurs when a user minimizes the app.](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/run-in-the-background-indefinetly)

This sounds similar to Android: When apps are not being used / are minimized, they go into a suspended state. 

So I don't think it would be able to play audio when it's minimized since it's not quite running. (Though I'll have to play around with the [running in background setting in Unity](https://docs.unity3d.com/ScriptReference/Application-runInBackground.html) and test that on a non UWP build to fully confirm that functionality on Windows/Desktops)

---

Now, I can understand why we think the settings option does the reverse behavior. It's actually working as intended and not reversed...but I can see how the phrasing can confuse the intent. **The `Mute audio when out of focus` settings option only applies to the application. The sound that the Window's Notification makes, is _not_ part of this settings option.**

I presume the expected behavior is to play/hear a sound when the application is minimized/suspended? 
App sound or notification sound? 

App sound doesn't seem possible since the app is not really running as I said above, but we might be able to configure the notification to play its sound instead when the application is minimized/suspended.

We can create a `IsApplicationMinimized()` method and use that to decide which notification (alarm/no alarm) to prompt the user, like so:

```
if (IsApplicationMinimized() || settings.m_muteSoundWhenOutOfFocus)
{
    // Play Alarm Notification
}
```

This way when the app is minimized, the user can still hear some sort of sound when the timer does go off. (Regardless of the current `mute sound when out of focus` settings option). If users want to hide and mute the notification sound, they can suppress the notifications on the operating system side as well:
![image](https://user-images.githubusercontent.com/12757380/166183336-152f2b51-2460-47e4-9816-ea890d455fff.png)

--- 

Would playing a Windows Alarm Notification when the application is minimized solve your concern?

**Comment by rdelian** [comment]
> I presume the expected behavior is to play/hear a sound when the application is minimized/suspended?

Yes

> Would playing a Windows Alarm Notification when the application is minimized solve your concern?

Yes, It doesn't matter which sound it is as long as it's playing continuously until I manually dismiss it (so I don't miss it while I'm not close to my desk)

-----

If that's not possible I'll just switch to a non UWP build, didn't knew that's an option until now

**Comment by adrian-miasik** [comment]
I don't have my development environment setup at the moment, but I'll take a look at it later this week.
I'll keep you updated on development and any new findings.

Thanks again for bringing this to my attention, this is something I bet other users would also like to see incorporated as well. Good catch!

Talk soon.

**Comment by adrian-miasik** [comment]
I took a look at the current behaviors (v2.1.1) on the specific platforms and filled out these tables:

# UWP
| State                                                   | Settings Option: `Mute audio when out of focus` | Behavior                                            |
| ------------------------------------------------------- | ----------------------------------------------- | --------------------------------------------------- |
| Minimized                                               | Yes                                             | Notification Prompt w/ Alarm Sound                  |
| Minimized                                               | No                                              | Notification Prompt w/ No Sound                     |
| Running in background (Out of focus, but not minimized) | Yes                                             | Notification Prompt w/ Alarm Sound                  |
| Running in background (Out of focus, but not minimized) | No                                              | Application Beeps + Notification Prompt w/ No Sound |

# Desktop
| State                                                   | Settings Option: `Mute audio when out of focus` | Behavior          |
| ------------------------------------------------------- | ----------------------------------------------- | ----------------- |
| Minimized                                               | Yes                                             | No Prompt         |
| Minimized                                               | No                                              | Application Beeps |
| Running in background (Out of focus, but not minimized) | Yes                                             | No Prompt         | 
| Running in background (Out of focus, but not minimized) | No                                              | Application Beeps |

---
The UWP versions don't behave the way you'd want them to when minimized due to their suspended state. Due to the nature of Universal Windows Platform apps and how they cannot "run in the background", I'm going to recommend you use the desktop version (non-UWP) instead. [Here's release v2.1.1 - Use 32/64-bit depending on your system architecture.](https://github.com/adrian-miasik/unity-pomodoro/releases/tag/v2.1.1)

As you can see in the Desktop table, when the application is minimized and the `mute audio when out of focus` settings option is set to off (which is the default setting for our desktop build), you will be able to hear constant beeps from the app until you stop the timer yourself. Maybe in the future I can add a taskbar prompt/flashing for when the timer is completed, but once again there isn't anything like that in the Unity API so that would require some work with external C# libraries and windows DLL's probably.

The downside to switching to the Desktop version instead of using the UWP version, is that you lose automatic updates via the Microsoft Store, and you don't get OS specific notifications or prompts (In fact you get none at all) - You'd solely be relying on audio.

**Comment by adrian-miasik** [comment]
Ah, one more thing I can suggest is that if you do stick to the UWP version, you can get `Application Beeps + Notification Prompt w/ No Sound` if you don't minimize the window. Instead focus on another window and let the app churn in the background. This way you can continue to hear the application as you'd expect it to and continue to receive the UWP benefits of updates and a notification prompt.

Make sure to leave the `mute audio when out of focus` settings option to `disabled` though.

Hope this helps! Best of luck.
